### ISSUE TITLE
Add back windows support?

### ISSUE THREAD

**Issue by Borwe** [near/create-near-app#2074]
I just noticed that the new version doesn't support windows, but old one I had on my system used to.
I now can't use this since WSL2 won't run on my Windows install due to low RAM.
Was wondering if PRs are open to add it back? Or why was it removed?

**Comment by frol** [comment]
@Borwe I don't have Windows, and I guess it was not a conscious action that caused this regression. We are open for PRs!

**Comment by Borwe** [comment]
I have a fork working for pure windows, but it fails at npm install of `intergration-tests`, I am wondering if I could create a PR, that when RUN on windows, it would warn the user about breakage when trying to use intergration tests in the genreation process, would that be okay?

**Comment by frol** [comment]
@Borwe Sounds list a reasonable workaround to me, but can you dig and report the root cause for the issue?

**Comment by Borwe** [comment]
(Here)[https://github.com/near/near-workspaces-js/issues/201] is the root cause, seems it's a sandbox proble.

**Comment by ChaoticTempest** [comment]
For context, sandbox cannot be supported on windows due to nearcore not being compilable/supported on windows. There's a potential way to get it working on windows, but all tests would have to be pointed to `testnet`. There's a feature in https://github.com/near/near-workspaces-rs that supports not utilizing a sandbox and only purely working with `mainnet` and `testnet`

**Comment by frol** [comment]
I see, well, I don't expect anyone to put their effort into making nearcore to operate on Windows, but I also don't see near-workspaces-js in the dependency tree of `create-near-app`. @Borwe Can you provide a screenshot of what you are running and the error? PR is also welcome

**Comment by Borwe** [comment]
Unfortunately I am back on a Windows machine lol. @frol here is the location where near-workspaces is used.
[here](https://github.com/near/create-near-app/blob/f804ff314719e631e2f264c9bc94634c2dd0bf05/templates/contracts/ts/package.json#L17)

And now that there is rust for itnergration tests [here it is too](https://github.com/near/create-near-app/blob/f804ff314719e631e2f264c9bc94634c2dd0bf05/templates/contracts/rs/Cargo.toml#L20)

I tried compiling the rust version to track where exactly it is failing, it all boils down to this [line](https://github.com/near/near-sandbox/blob/4ca9c1fac434b75ee40c890cda5edd47ce86ead2/crate/src/lib.rs#L46)
`platform()`, returns None since on Windows, but I was wondering if we could use some kind of a docker wrapper for windows? Since all that seems to do essentially is download a blob from the internet, which can be traced back to the
[call](https://github.com/near/near-workspaces-rs/blob/97d644983c0302b737e7d0787b554b5e7efe420a/workspaces/build.rs#L7).

**Comment by gagdiez** [comment]
we took some time to study this on depth and apparently it would not be possible since multiple packages are not compatible with windows (the most important ones being `near-sdk-rs` and `near-workspaces`

Because of this we will not be able to bring back windows support. To mitigate problems, we decided to write a guide on how to use `WSL` on windows and added it to our quickstart guide

**Comment by gagdiez** [comment]
@frol I changed the message to point towards the blogpost 2 weeks ago:

https://github.com/near/create-near-app/blob/9c482fd0871a206fae04dabc3e91fb775d9b88f9/src/messages.ts#L127

I'll check now if our frontend works on windows

**Comment by gagdiez** [comment]
@frol good catch: https://github.com/near/create-near-app/issues/2155
